---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
  namespace: pdb
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi