---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
  labels:
    type: local
    app: pdb
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany  
  hostPath:
    path: "/data/db"